apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgw
  labels:
    app: pushgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgw
  template:
    metadata:
      labels:
        app: pushgw
    spec:
      initContainers:
      - name: init-redis
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redis.redis.svc.cluster.local; do echo waiting for redis; sleep 2; done"]
      containers:
      - name: master
        image: docker.io/dmitsh/pushgatewayredis:0.1
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/pushgateway"]
        args: ["--redis.endpoint", "redis.redis.svc.cluster.local:6379", "--redis.expiration", "1h"]
        ports:
        - containerPort: 9753
---
apiVersion: v1
kind: Service
metadata:
  name: pushgw
  labels:
    app: pushgw
spec:
  clusterIP: None
  ports:
  - port: 9753
  selector:
    app: pushgw
